### ISSUE TITLE
chart zooming

### ISSUE THREAD

**Issue by rradu92** [jhuckaby/pixl-chart#2]
Hello,

First of all, thanks for this library, i'm using it in an embedded device with lot of sensor data charts and it works very well.

Right now i'm using it in conjunction with a slider to zoom in and recalculate the start and end position to get from backend, I see something related with zooming in the documentation but i'm not able to see how it works or how to use the zoom function.

I would like to be able to zoom in and out with the wheel in desktop and with two fingers in mobile, and update the dataset based on it.

Do you think would be possible to provide an example like the other ones you provided for almost all use cases or give me a hint about how the zooming function whould have to work?

Thanks

**Comment by jhuckaby** [comment]
Hi there!

So, pixl-chart gives you the basic underlying API by exposing a "zoom" configuration object that you can manipulate to zoom in your dataset in response to user actions:

https://github.com/jhuckaby/pixl-chart#zooming

Using this you can implement your own zoom system.  For example, here is a demo showing a click-to-zoom implementation:

https://pixlcore.com/software/pixl-chart/demos/click-to-zoom.html

It would be fairly straightforward to add mouse-wheel support to this.  Just listen for the mousewheel event, calculate the wheel delta amount, and apply that to the xMin and yMin calculation that happens on click:

```js
// center new zoom area around mouse cursor (tooltip epoch)
chart.zoom.xMin = chart.tooltip.epoch - Math.floor(limits.width / 4);
chart.zoom.xMax = chart.tooltip.epoch + Math.floor(limits.width / 4);
```

Instead of `limits.width / 4`, a mousewheel event is probably much more "fine grain" than a mouse click, so maybe divide it by 10 or something.  If the mouse wheel moves in the other direction (i.e. zoom out) reverse the polarity of the `-` and `+` (have xMin go positive and xMax go negative).

The rest of the implementation is left as an exercise for the reader.

Good luck!

**Comment by rradu92** [comment]
Thanks you very much, it works flawlessly!
